annonce_immobilier_admin/routes/web.php
<?php

use App\Http\Controllers\AnnonceController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::resource("annonce",AnnonceController::class);

annonce_immobilier_admin/app/Models/Annonce.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Annonce extends Model
{
    
    const types = ['Appartement', 'Maison', 'Villa', 'Magasin', 'Terrain'];
    protected $guarded=[];
    use HasFactory;
}

annonce_immobilier_admin/app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

annonce_immobilier_admin/app/Http/Controllers/AnnonceController.php
<?php

namespace App\Http\Controllers;

use App\Models\Annonce;
use Illuminate\Http\Request;

class AnnonceController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $annonces=Annonce::all();
        return view('annonce.index',compact("annonces"));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        return view('annonce.create');
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $annonce=Annonce::create([
            "titre"=>$request->titre,
            "description"=>$request->description,       
            "type"=>$request->type,       
            "ville"=>$request->ville,       
            "superficie"=>$request->superficie,        
            "prix"=>$request->prix,        
        ]);
        return redirect()->route('annonce.index')->with("succes","l'annonce a ete ajoute !");
    }

    /**
     * Display the specified resource.
     */
    public function show(Annonce $annonce)
    {
        return view("annonce.show", compact("annonce"));
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Annonce $annonce)
    {
        return view("annonce.edit", compact("annonce"));
   
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, Annonce $annonce)
    {
        $annonce->update($request->all());
        return redirect()->route('annonce.index')->with('success','Le stagiaire a été modifié avec succès.');

    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Annonce $annonce)
    {
        $annonce->delete();
        return redirect()->route('annonce.index')->with('success','Annonce supprimée avec succès !');
    }
}

annonce_immobilier_admin/app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, ValidatesRequests;
}

annonce_immobilier_admin/resources/views/annonce/create.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    
    <title>index</title>
</head>
<body>
<h1>Nouvelle annonce</h1>
<form action="{{route('annonce.store')}}" method="post" class="col-8">
    @csrf
    <div class="mb-3">
            <label class="form-label" for="titre">Titre</label>
            <input type="text" class="form-control" name="titre" id="titre">
        </div>
          <div class="mb-3">
            <label class="form-label" for="description">Description</label>
            <input type="text" class="form-control" name="description" id="description">
        </div>
          <div class="mb-3">
            <label class="form-label" for="type">Type</label>
            <select name="type" class="form-select">
              <option value="Appartement">Appartement</option>
              <option value="Maison">Maison</option>
              <option value="Villa">Villa</option>
              <option value="Magasin">Magasin</option>
              <option value="Terrain">Terrain</option>
            </select>
        </div>
          <div class="mb-3">
            <label class="form-label" for="ville">Ville</label>
            <input type="text" class="form-control" name="ville" id="ville">
        </div>
          <div class="mb-3">
            <label class="form-label" for="superficie">Superficie</label>
            <input type="text" class="form-control" name="superficie" id="superficie">
        </div>
          <div class="mb-3">
            <label class="form-label" for="prix">Prix</label>
            <input type="text" class="form-control" name="prix" id="prix">
        </div>
        <input type="submit" value="Ajouter" class="btn btn-primary">
    
</form>
</body>
</html>

annonce_immobilier_admin/resources/views/annonce/edit.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <title>Modification</title>
</head>
 
<body class="container mt-2">
<h2>Modification de l'annonce</h2>
<form action="{{route('annonce.update',$annonce->id)}}" method="post" class="col-8">
    @csrf
    @method('PUT')
    <div class="mb-3">
            <label class="form-label" for="titre">Titre</label>
            <input type="text" class="form-control" name="titre" id="titre" value="{{$annonce->titre}}">
        </div>
          <div class="mb-3">
            <label class="form-label" for="description">Description</label>
            <input type="text" class="form-control" name="description" id="description" value="{{$annonce->description}}" />
        </div>
          <div class="mb-3">
            <label class="form-label" for="type">Type</label>
            <input type="text" class="form-control" name="type" id="type" value="{{$annonce->type}}"/>
        </div>
          <div class="mb-3">
            <label class="form-label" for="ville">Ville</label>
            <input type="text" class="form-control" name="ville" id="ville"  value="{{$annonce->ville}}"/>
        </div>
          <div class="mb-3">
            <label class="form-label" for="superficie">Superficie</label>
            <input type="text" class="form-control" name="superficie" id="superficie"  value="{{$annonce->superficie}}"/> 
        </div>
          <div class="mb-3">
            <label class="form-label" for="prix">Prix</label>
            <input type="text" class="form-control" name="prix" id="prix" value="{{$annonce->prix}}"/>
        </div>
  <button type="submit" class="btn btn-primary">Enregistrer</button>
    
</form>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>

</body>
</html>

annonce_immobilier_admin/resources/views/annonce/index.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
    <title>index</title>
    <style>
        .red-bg {
  background-color: red;
  padding: 5px;
  border-radius: 25%;
}
    </style>
</head>
<body>
    
<h1>liste des annonces</h1>
<!-- @if(session('success')) -->
    <!-- <div class="alert alert-success">{{ session('success') }}</div>
    <script>
        setTimeout(function(){
            $('.alert-success').fadeOut();
        }, 3000);
    </script> -->
<!-- @endif -->
@if ($message = Session::get('success'))
            <div class="alert alert-success">
                <p>{{ $message }}</p>
            </div>
            
        @endif
<a href="{{route('annonce.create')}}"  class="btn btn-primary">Nouvelle annonce</a>
@isset($annonces)
<table class="table mt-3">
<tr>
    <th>Titre</th>
    <th>Description</th>
    <th>Type</th>
    <th>Ville</th>
    <th>Superficie</th>
    <th>etat</th>
    <th>Prix(dhs)</th>
    <th>Action</th>
</tr>
@foreach($annonces as $annonce )
    <tr>
        <td>{{$annonce->titre}}</td>
        <td>{{$annonce->description}}</td>
        <td>{{$annonce->type}}</td>
        <td>{{$annonce->ville}}</td>
        <td>{{$annonce->superficie}}</td>
        <td>{{$annonce->neuf}}</td>
        <td>{{$annonce->prix}}</td>
        <td>
        <form method="post" action="{{route('annonce.destroy', $annonce->id)}}"  onsubmit="return confirm('Voulez-vous vraiment supprimer cette annonce ?');">
								@csrf
								@method('DELETE')
								<a href="{{ route('annonce.show', $annonce->id) }}" class="btn btn-light btn-sm "><i class="bi bi-list"></i></a>
								<a href="{{ route('annonce.edit', $annonce->id) }}" class="btn btn-light btn-sm bg-success"><i class="bi bi-pencil"></i></a>
								<!-- <input type="submit" class="bi bi-trash3-fill" /> -->

                                <button type="submit" style="border: none; " class="red-bg"><i class="bi bi-trash"></i></button>
							</form>
        </td>
    </tr>
    @endforeach
</table>
@endisset
</body>

</html>

annonce_immobilier_admin/resources/views/annonce/show.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
 
    <title>Document</title>
</head>
<body>
<div class="container mt-4 w-50">
        <h2> Détails</h2>
        <div class="form-group">
           <strong>Titre :</strong>
           {{ $annonce->titre}}
        </div>
        <div class="form-group">
            <strong>Description:</strong>
            {{ $annonce->description }}
        </div>
        <div class="form-group">
            <strong>type :</strong>
            {{ $annonce->type }}
        </div>
        <div class="form-group">
            <strong>ville :</strong>
            {{ $annonce->ville }}
        </div>
        <div class="form-group">
            <strong>superficie :</strong>
            {{ $annonce->superficie }}
        </div>
        
       </div>
 
</body>
</html>